### PR TITLE
obfuscating procedures and medication statements

### PR DESCRIPTION
**Pull request by enola-dkfz**

### CODE REVIEW

**Comment by enola-dkfz** [comment]
Before merging test in 1 DKTK BH

**Comment by Threated** [comment]
Consider putting your large constants in some external files and import them using:
```rust
const MY_STR: &str = include_str!("../path/to/file.json");
```

**Review by TKussel — APPROVED** [review]
We need to add to our backlog:

- Develop a more scalable way for parameter ingestion
- Refactor for increased generalization
- Include long test jsons as files (as per @Threated 's comment)
-

**Comment by enola-dkfz** [comment]
> Consider putting your large constants in some external files and import them using:
> 
> ```rust
> const MY_STR: &str = include_str!("../path/to/file.json");
> ```

did so

**Pull request merged**
