### PR TITLE
Update util.rs

### PR DESCRIPTION
**Pull request by davidmscholz**
update exliquid CQL so that only primary samples are taken into account with at least one aliquot with amountrest(aliquot) > 0.

### CODE REVIEW

**Comment by Threated** [comment]
@enola-dkfz is it fine that everyone pushing to main or should they merge to develop. Develop also has the CI improvements that run the tests.

**Comment by enola-dkfz** [comment]
Yes, that's the only way to test it for now

**Review by Threated — CHANGES_REQUESTED** [review]
The test are not passing. If you have a rust setup you can run them yourself with `cargo test` if not you can make a PR against the develop branch where the CI will run the tests for you.

**Comment by davidmscholz** [comment]
thx. will do

**Pull request closed without merging**
